# Generated by Django 5.0.7 on 2024-08-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlis_app', '0006_review_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='avg_arting',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
    ]
